In [2]:
import numpy as np 
import pandas as pd 
import os

In [3]:
os.getcwd()

'/Users/yoganandhrau/Document/Projects/semicon-yield-pipeline/notebooks'

In [9]:
df_sensors = pd.read_csv("../data/secom/secom.data", sep=r"\s+", header=None)
df_labels = pd.read_csv("../data/secom/secom_labels.data", sep=r"\s+", header=None)

In [10]:
print(df_sensors.shape)
print(df_labels.shape)

(1567, 590)
(1567, 2)

In [11]:
df_sensors.head()

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,0.0060,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,0.0148,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,0.0044,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432

In [12]:
df_labels.head()

   0                    1
0 -1  19/07/2008 11:55:00
1 -1  19/07/2008 12:32:00
2  1  19/07/2008 13:17:00
3 -1  19/07/2008 14:43:00
4 -1  19/07/2008 15:22:00

In [13]:
df_sensors.isnull().sum().sum()

np.int64(41951)

In [14]:
with open("../data/secom/secom.names", "r") as f:
    print(f.read())

Title: SECOM Data Set

Abstract: Data from a semi-conductor manufacturing process


-----------------------------------------------------

Data Set Characteristics: Multivariate
Number of Instances: 1567
Area: Computer
Attribute Characteristics: Real
Number of Attributes: 591
Date Donated: 2008-11-19
Associated Tasks: Classification, Causal-Discovery
Missing Values? Yes

-----------------------------------------------------

Source:

Authors: Michael McCann, Adrian Johnston

-----------------------------------------------------

Data Set Information:

A complex modern semi-conductor manufacturing process is normally under consistent
surveillance via the monitoring of signals/variables collected from sensors and or
process measurement points. However, not all of these signals are equally valuable
in a specific monitoring system. The measured signals contain a combination of
useful information, irrelevant information as well as noise. It is often the case
that useful information is buried in the latter two. Engineers typically have a
much larger number of signals than are actually required. If we consider each type
of signal as a feature, then feature selection may be applied to identify the most
relevant signals. The Process Engineers may then use these signals to determine key
factors contributing to yield excursions downstream in the process. This will
enable an increase in process throughput, decreased time to learning and reduce the
per unit production costs.

To enhance current business improvement techniques the application of feature
selection as an intelligent systems technique is being investigated.

The dataset presented in this case represents a selection of such features where
each example represents a single production entity with associated measured
features and the labels represent a simple pass/fail yield for in house line
testing, figure 2, and associated date time stamp. Where .1 corresponds to a pass
and 1 corresponds to a fail and the data time stamp is for that specific test
point.


Using feature selection techniques it is desired to rank features according to
their impact on the overall yield for the product, causal relationships may also be
considered with a view to identifying the key features.

Results may be submitted in terms of feature relevance for predictability using
error rates as our evaluation metrics. It is suggested that cross validation be
applied to generate these results. Some baseline results are shown below for basic
feature selection techniques using a simple kernel ridge classifier and 10 fold
cross validation.

Baseline Results: Pre-processing objects were applied to the dataset simply to
standardize the data and remove the constant features and then a number of
different feature selection objects selecting 40 highest ranked features were
applied with a simple classifier to achieve some initial results. 10 fold cross
validation was used and the balanced error rate (*BER) generated as our initial
performance metric to help investigate this dataset.


SECOM Dataset: 1567 examples 591 features, 104 fails

FSmethod (40 features) BER % True + % True - %
S2N (signal to noise) 34.5 +-2.6 57.8 +-5.3 73.1 +2.1
Ttest 33.7 +-2.1 59.6 +-4.7 73.0 +-1.8
Relief 40.1 +-2.8 48.3 +-5.9 71.6 +-3.2
Pearson 34.1 +-2.0 57.4 +-4.3 74.4 +-4.9
Ftest 33.5 +-2.2 59.1 +-4.8 73.8 +-1.8
Gram Schmidt 35.6 +-2.4 51.2 +-11.8 77.5 +-2.3

-----------------------------------------------------

Attribute Information:

Key facts: Data Structure: The data consists of 2 files the dataset file SECOM
consisting of 1567 examples each with 591 features a 1567 x 591 matrix and a labels
file containing the classifications and date time stamp for each example.

As with any real life data situations this data contains null values varying in
intensity depending on the individuals features. This needs to be taken into
consideration when investigating the data either through pre-processing or within
the technique applied.

The data is represented in a raw text file each line representing an individual
example and the features seperated by spaces. The null values are represented by
the 'NaN' value as per MatLab.

In [18]:
missing_per_sensor = df_sensors.isnull().sum()
print(missing_per_sensor.describe())

count     590.000000
mean       71.103390
std       241.850565
min         0.000000
25%         2.000000
50%         6.000000
75%         9.000000
max      1429.000000
dtype: float64

In [19]:
df_sensors.isnull().mean()

0      0.003829
1      0.004467
2      0.008934
3      0.008934
4      0.008934
         ...
585    0.000638
586    0.000638
587    0.000638
588    0.000638
589    0.000638
Length: 590, dtype: float64

In [21]:
for threshold in [10, 20, 30, 40, 50]:
    pct = threshold / 100
    n_dropped = (df_sensors.isnull().mean() > pct).sum()
    print(f"Threshold {threshold}% : {n_dropped} sensors dropped")

Threshold 10% : 52 sensors dropped
Threshold 20% : 32 sensors dropped
Threshold 30% : 32 sensors dropped
Threshold 40% : 32 sensors dropped
Threshold 50% : 28 sensors dropped